# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
---
shared:
  image: vespaengine/vespa-build-centos-stream8:latest
  environment:
    USER_SHELL_BIN: bash

jobs:
  build-vespa:
    requires: [~pr]
    image: docker.io/vespaengine/vespa-build-centos-stream8:latest
    annotations:
      screwdriver.cd/cpu: 7
      screwdriver.cd/ram: 16
      screwdriver.cd/disk: HIGH
      screwdriver.cd/timeout: 90
      screwdriver.cd/buildPeriodically: H 4 * * *
      screwdriver.cd/dockerEnabled: true

    environment:
      LOCAL_MVN_REPO: "/tmp/vespa/mvnrepo"
      VESPA_MAVEN_EXTRA_OPTS: "-Dmaven.repo.local=/tmp/vespa/mvnrepo -Dmaven.source.skip=true"
      CCACHE_TMP_DIR: "/tmp/ccache_tmp"
      CCACHE_DATA_DIR: "/tmp/vespa/ccache"
      MAIN_CACHE_FILE: "/main_job_cache/vespa.tar"
    secrets:
      - DOCKER_HUB_DEPLOY_KEY
      - SVC_OKTA_VESPA_FACTORY_TOKEN
      - COPR_WEBHOOK
      - OSSRH_USER
      - OSSRH_TOKEN
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_ENCPHRASE
      - SAMPLE_APPS_DEPLOY_KEY
      - VESPA_DEPLOY_KEY
      - DOCKER_IMAGE_DEPLOY_KEY
      - DOCKER_HUB_DEPLOY_KEY
      - GHCR_DEPLOY_KEY
      - SVC_OKTA_VESPA_FACTORY_TOKEN
      - HOMEBREW_GITHUB_API_TOKEN
      - GH_TOKEN
      - JFROG_API_TOKEN
    steps:
      - inspect: |
          cat /.dockerenv
      - install-dependencies: |
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce docker-ce-cli containerd.io
          docker system info
          docker ps -a
          docker images -a
          ps -Af
