# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.16-alpine

options:
  docker: true

definitions:
  steps:
    - step: &test
        script:
          - CGO_ENABLED=0 go test -covermode=count -timeout=30s ./...
    - step: &lint
        script:
          - apk add --update git
          - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
          - GO111MODULE=on CGO_ENABLED=0 golangci-lint run --config .golangci.yml

pipelines:
  default:
    - step: *test
    - step: *lint
  tags:
    "v*.*.*":
      - step: *test
      # - step: *lint
  branches:
    master:
      - step: *test
      - step: *lint
